services:

  back:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/src/static
      - media_volume:/src/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  front:
    build: ./frontend
    command: npm start
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env

  redis:
    image: redis:6
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"


volumes:
  redis_data:
  static_volume:
  media_volume:
