# Generated by Django 4.2.20 on 2025-04-25 11:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('status', models.CharField(choices=[('1', 'В обработке'), ('2', 'В пути'), ('3', 'Готов'), ('4', 'Отменён')], default='1', max_length=50, verbose_name='Статус заказа')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='Сумма заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Телефонный номер должен быть представлен в виде +79999999999 (11 цифр)', regex='^(?:\\+7|8)\\d{10}$')])),
                ('address', models.CharField(max_length=100, verbose_name='Адрес заказчика')),
                ('name_client', models.CharField(max_length=100, verbose_name='ФИО заказчика')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Зазачик')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'default_related_name': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество товара')),
                ('total_price', models.PositiveIntegerField(blank=True, verbose_name='Конечная стоимость товаров')),
                ('price', models.PositiveIntegerField(blank=True, verbose_name='Cтоимость товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар заказа',
                'verbose_name_plural': 'Товары заказа',
            },
        ),
    ]
