# Generated by Django 4.2.20 on 2025-05-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Скидка в процентах'),
        ),
    ]
